[project]
name = "agno-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.3.22",
    "agno>=2.4.0",
    "aiohttp>=3.11.18",
    "anthropic>=0.51.0",
    "arxiv>=2.2.0",
    "azure-ai-inference>=1.0.0b9",
    "chonkie[st]>=1.0.8",
    "cohere>=5.15.0",
    "ddgs>=9.10.0",
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "lancedb>=0.22.1",
    "lxml-html-clean>=0.4.2",
    "lxml[clean]>=6.0.0",
    "mcp>=1.0.0",
    "newspaper4k>=0.9.3.1",
    "ollama>=0.4.8",
    "openai>=2.0.0",
    "praw>=7.8.1",
    "pyjwt>=2.11.0",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0.41",
    "tantivy>=0.24.0",
    "yfinance>=1.0.0",
]

[dependency-groups]
dev = [
    "certifi>=2025.4.26",
]
